//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreMain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batch
    {
        public int b_id { get; set; }
        public string batch_code { get; set; }
        public Nullable<int> d_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public int quantity_inhand { get; set; }
        public System.DateTime expiry_date { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual Product Product { get; set; }
    }
}
