//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreMain.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GroceryStoreDBEntities : DbContext
    {
        public GroceryStoreDBEntities()
            : base("name=GroceryStoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Cart_Product_Assoc> Cart_Product_Assoc { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Customer_Address> Customer_Address { get; set; }
        public virtual DbSet<Delivery_Time_Slot> Delivery_Time_Slot { get; set; }
        public virtual DbSet<Discount> Discounts { get; set; }
        public virtual DbSet<Distributor> Distributors { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Order_Status> Order_Status { get; set; }
        public virtual DbSet<OTP_History> OTP_History { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Product_Category> Product_Category { get; set; }
        public virtual DbSet<Unit_Of_Measurement> Unit_Of_Measurement { get; set; }
        public virtual DbSet<Feedback_test> Feedback_test { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Recipe_Step> Recipe_Step { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    }
}
