//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreMain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        public int dt_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public int discount_percentage { get; set; }
        public Nullable<System.DateTime> eff_start_dtm { get; set; }
        public Nullable<System.DateTime> eff_end_dtm { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
