//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreMain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback_test
    {
        public int f_id { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public string feedback { get; set; }
        public Nullable<int> rating { get; set; }
    }
}
