//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreMain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int od_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> d_id { get; set; }
        public Nullable<int> o_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public decimal total_amt { get; set; }
    
        public virtual Distributor Distributor { get; set; }
        public virtual Product Product { get; set; }
        public virtual Order Order { get; set; }
    }
}
