//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryStoreMain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP_History
    {
        public int otp_id { get; set; }
        public decimal otp { get; set; }
        public int c_id { get; set; }
        public System.DateTime eff_startdtm { get; set; }
        public System.DateTime eff_enddtm { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
